config/routes.rb
Rails.application.routes.draw do
    root 'offers#index'

    get "/auth/:provider/callback" => "sessions#create"
    get "/signout" => "sessions#destroy"
    get "/about" => "offers#about"

    resources :offers do
        get 'mine', on: :collection

        resources :replies, only: [:create, :destroy]
    end

    resources :replies, only: [:index] do
        get 'choose', on: :collection
        patch 'read', on: :collection
    end

    resources :users, only: [:avatars] do
        get 'avatars', on: :member
    end

    namespace :admin do
        root :to => "offers#index"
        resources :offers do
            patch 'accept', on: :member
        end
    end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  has_many :replies

  acts_as_paranoid

  validates :content,
      presence: true,
      length: { maximum: 140 }
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :offer
  belongs_to :user

  validates :message,
      presence: true,
      length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :offers
  has_many :replies

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
    end
  end
end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < AdminController
	before_action :require_auth, :require_admin

	def index
		@offers = Offer.all.order('created_at DESC')
	end

	def create
		uid = params[:user_uid]
		if uid.present?
			user = User.where(uid: uid).first
			if not user.present?
				user = User.create!(uid: uid, provider: 'vkontakte')
			end	
			@offer = user.offers.create(offer_params)
		else
			@offer = current_user.offers.create(offer_params)
		end
	    redirect_to admin_offers_path
	end

	def destroy
		@offer = Offer.find(params[:id])
		@offer.destroy
	end

	def accept
		@offer = Offer.find(params[:id])
		@offer.update(accepted: Time.now)
	end

	private
	    def offer_params
			params.require(:offer).permit(:content)
	    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :requires_auth
  helper_method :vk_api

  private
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_auth
        redirect_to root_path if not current_user
    end

    def vk_api
        @vk_api = VkontakteApi::Client.new
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_auth, except: [:index, :about]

  def index
    @offers = Offer.where.not(accepted: nil).order('created_at DESC')
  end

  def create
    @offer = current_user.offers.create(offer_params).save
    redirect_to offers_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
  end

  def mine
    @offers = current_user.offers.order('created_at DESC')
  end

  def about
  end

  private
    def offer_params
      params.require(:offer).permit(:content)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :require_auth

  def index
    @offers = current_user.offers.order('created_at DESC')
    @offer = @offers.first
    @replies = @offer ? @offer.replies.order('created_at DESC') : []
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @reply = @offer.replies.create(reply_params).save
  end

  def destroy
    @reply = Reply.find(params[:id])
    @offer = @reply.offer
    if @reply.user == current_user
      @reply.destroy
    end
  end

  def choose
    @offers = current_user.offers.order('created_at DESC')
    @offer = Offer.find(params[:offer_id])
    @replies = @offer ? @offer.replies.order('created_at DESC') : []
  end

  def read
    @offers = current_user.offers.order('created_at DESC')
    @offer = Offer.find(params[:offer_id]) 
    ids = params[:ids]
    @replies = Reply.where(id: ids).order('created_at DESC')
    @replies.each do |reply|
      reply.update(seen: Time.now) if reply.offer.user == current_user
    end
  end

  private
    def reply_params
      params.require(:reply).permit(:message).merge(user: current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def avatars
        photos_hash = vk_api.photos.get(
                owner_id: User.find(params[:id]).uid,
                album_id: "profile",
                rev: true
                )
        @photos = []
        photos_hash.each do |photo|
            @photos.push photo[:src_big]
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
    def new_replies
      Reply.joins(:offer).merge(Offer.where(user: current_user)).merge(Reply.where(seen: nil)).count
    end

	def new_replies_offer offer
      offer.replies.where(seen: nil).count
    end
end

app/helpers/time_helper.rb
module TimeHelper
    def current_time timestamp
      timestamp + 3.hours
    end

    def pretty_time timestamp
      timestamp = current_time timestamp
      
      if Time.now - timestamp < 5.minutes
        t('recently')
      elsif timestamp.to_date == Date.today
        l(timestamp, format: :time_only)
      elsif timestamp.to_date == Date.yesterday
        t('yesterday') + ", " + l(timestamp, format: :time_only )
      elsif timestamp.to_date.year == Date.today.year
        l(timestamp, format: :short)
      else
        l timestamp, format: :short_with_year
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user_avatar
        user_hash = vk_api.users.get(user_ids: current_user.uid, fields: 'photo_100', https: 1)[0]

        image_tag(user_hash[:photo_100], id: "nav-avatar", class: "img-circle")
    end
    def avatar(user)
        user_hash = vk_api.users.get(user_ids: user.uid, fields: 'photo_100', https: 1)[0]

        link_to(avatars_user_path(user), remote: true, class: "media-left") do
            image_tag(user_hash[:photo_100], class: 'media-object avatar', alt: "Avatar")
        end
    end
    def user_link(user)
        user_hash = vk_api.users.get(user_ids: user.uid, fields: 'domain', lang: 0)[0]

        link_to user_hash[:first_name] + ' ' + user_hash[:last_name], "https://vk.com/" + user_hash[:domain]
    end
end

app/views/admin/offers/_offer.html.erb
<div class="offer media-style" data-id="<%= offer.id %>">
	<div class="media">
		<div class="media-left">
	    	<%= avatar(offer.user) %>
	    </div>
	    <div class="media-body">
	    		<div class="offer-content">
				    <%= offer.content %>
				</div>
				<div class="created-at" data-id="<%= offer.id %>">
				    <%= pretty_time offer.created_at %>
				</div>

				<div class="offer-reply media-controls" data-id="<%= offer.id %>">
				      <div class="offer-delete media-controls">
				        <%= link_to t('delete'),
				            admin_offer_path(offer),
				            remote: true,
				            method: :delete,
				            data: { confirm: t('sure') } %>
			            <% if !offer.accepted %>
					        <%= link_to t('accept'),
					            accept_admin_offer_path(offer),
					            remote: true,
					            method: :patch,
					            data: { confirm: t('sure') } %>
			      		<% end %>
				      </div>
				</div>
		</div> <!-- /.media-body -->
	</div>
</div> 

app/views/admin/offers/accept.js.erb
$('.offer[data-id=<%= @offer.id %>]').replaceWith("<%= j (render partial: 'offer', locals: {offer: @offer}) %>")

app/views/admin/offers/destroy.js.erb
$('.offer[data-id=<%= @offer.id %>]').remove()

app/views/admin/offers/index.html.erb
<div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <% if current_user %> <!-- offer form -->
                    <div class="media media-style">
                        <div class="media-left">
                            <%= avatar(current_user) %>    
                        </div>
                        <div class="media-body">
                                    <%= form_for(Offer.new, url: {controller: "admin/offers", action: "create"}) do |f| %>
                                    <%= text_field_tag 'user_uid', nil, class: 'form-control' %>
                                    <%= f.text_area :content, class: "form-control", maxlength: "140" %>
                                    <div class="media-controls">
                                        <%= f.submit t('offer'), id: "btn-offer-submit", class: "btn-media-control btn btn-primary" %>
                                    </div>
                                <% end %>
                        </div> <!-- /.media-body -->
                    </div>
                <% end %>

                <% if @offers.length > 0 %> <!-- offers list -->
                    <div class="offer-list">
                        <%= render partial: "offer", collection: @offers %>
                    </div>
                <% else %>
                    <div class="empty-offer-list">
                        <%= t('no_offers') %>
                    </div>
                <% end %>
        </div> <!-- /.col -->
    </div> <!-- /.row -->
</div> <!-- /.container -->

app/views/layouts/_navbar.html.erb
<div class="navbar bg-faded">
        <%= link_to root_path, class:"navbar-brand" do %>
            <img src="/logo.svg" id="logo" alt="logo">
            <span><%= t('title') %></span>
        <% end %>
        <button type="button" class="pull-xs-right navbar-toggle"
          data-toggle="collapse" data-target=".navbar-collapse">
          <% if current_user %>
              <i class="fa fa-bars" aria-hidden="true"></i>
              <% if new_replies > 0 %>
                <span id="nav-extender-replies" class="tag tag-pill tag-warning"><%= new_replies %></span>
              <% end %>
          <% end %>
        </button>
        <ul id="desktop-nav" class="nav navbar-nav">
        <% if current_user %>
            <li class="nav-item">
                <%= link_to replies_path, id: "replies-link", class:"nav-link" do %>
                    <%= t('replies') %>
                    <% if new_replies > 0 %>
                        <span class="tag tag-pill tag-warning"><%= new_replies %></span>
                    <% end %>   
                <% end %>
            </li>

            <li class="nav-item">
                <%= link_to t('about'), about_path, class:"nav-link" %>
            </li>

            <div class="nav-current-user nav-item pull-sm-right">
                <%= current_user_avatar %>
                <%= link_to t('log_out'), signout_path, class:"nav-link nav-logout" %>
            </div>
        <% else %>
            <li class="nav-item">
                <%= link_to t('about'), about_path, class:"nav-link" %>
            </li>

            <li class="nav-item pull-xs-right">
                <%= link_to t('log_in'), "/auth/vkontakte", class:"nav-link"%>
            </li>
        <% end %>
      </ul>

      <div class="navbar-collapse collapse">
        <ul id="mobile-nav" class="nav navbar-nav">
        <% if current_user %>
            <li class="nav-item">
                <%= link_to t('replies'), replies_path, id: "replies-link-mobile", class:"nav-link" %>
                <% if new_replies > 0 %>
                    <span class="tag tag-pill tag-warning"><%= new_replies %></span>
                <% end %>
            </li>

            <li class="nav-item">
                <%= link_to t('about'), about_path, class:"nav-link" %>
            </li>

            <div class="nav-item">
                <%= link_to t('log_out'), signout_path, class:"nav-link" %>
            </div>
        <% else %>
            <li class="nav-item">
                <%= link_to t('about'), about_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to t('log_in'), "/auth/vkontakte", class:"nav-link"%>
            </li>
        <% end %>
      </ul>
      </div> <!-- /.navbar-collapse collapse -->
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= t('title') %></title>
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon16.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon32.png" />
  <link rel="icon" type="image/png" sizes="192x192" href="/favicon192.png" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.fontawesome.com/a98122c2dd.js"></script>
</head>
<body>

    <%= render "layouts/navbar" %>

    <%= yield %>

    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
    <div id="blueimp-gallery" class="blueimp-gallery">
        <!-- The container for the modal slides -->
        <div class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
        <!-- The modal dialog, which will be used to wrap the lightbox content -->
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body next"avatar(current_user)></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left prev">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            <%= t('prev') %>
                        </button>
                        <button type="button" class="btn btn-primary next">
                            <%= t('next') %>
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="gallery-links" style="display:none"></div>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-85799301-1', 'auto');
        ga('send', 'pageview');

    </script>
</body>
</html>

app/views/offers/_offer.html.erb
<div class="offer media-style" data-id="<%= offer.id %>">
	<div class="media">
		<div class="media-left">
	    	<%= avatar(offer.user) %>
	    </div>
	    <div class="media-body">
	    		<div class="offer-content">
				    <%= offer.content %>
				</div>
				<div class="created-at" data-id="<%= offer.id %>">
				    <%= pretty_time offer.accepted %>
				</div>
			    <%= render partial: 'offer_reply', locals: {offer: offer} %>
		</div> <!-- /.media-body -->
	</div>
	<%= render partial: 'offer_reply_form', locals: {offer: offer} %>
</div> 

app/views/offers/_offer_reply.html.erb
<div class="offer-reply media-controls" data-id="<%= offer.id %>">
  <% if current_user %>
    <% if not offer.user == current_user %>
      <% reply = offer.replies.where(user: current_user).first %>
      <% if not reply %>
        <a href="#" class="btn-reply" data-id="<%= offer.id %>" data-behavior="reply-button"><%=t('reply')%></a>
      <% else %>
        <%= link_to t('unreply'),
                offer_reply_path(offer, reply),
                remote: true,
                method: :delete,
                data: { confirm: t('sure') } %>
      <% end %> <!-- if current user replied offer -->
    <% else %>
      <div class="offer-delete media-controls">
        <%= link_to t('delete'),
            offer_path(offer),
            remote: true,
            method: :delete,
            data: { confirm: t('sure') } %>
      </div>
    <% end %> <!-- if current user did not create offer -->
  <% end %> <!-- if current user -->
</div>

app/views/offers/_offer_reply_form.html.erb
<% if current_user %>
	    <% if not offer.user == current_user %>
			<% reply = offer.replies.where(user: current_user).first %>
			<% if not reply %>
				<div class="media offer-reply-form" style="display:none" data-id="<%= offer.id %>" data-behavior="offer-reply-block">
					<div class="media-left">
						<%= avatar(current_user) %>
					</div>
					<div class="media-body">
						<%= form_for(Reply.new, url: offer_replies_url(offer), remote: true) do |f| %>
							<%= f.text_area :message, class: "form-control" %>
							<div class="media-controls">
								<%= f.submit t('reply'), class: "btn btn-primary btn-media-control" %>
								<input type="button" class="btn btn-default btn-media-control btn-cancel" value="<%=t('cancel')%>" data-id="<%= offer.id %>" data-behavior="cancel-reply-button">
							</div>
						<% end %>
		    		</div> <!-- /.media-body -->
				</div>
	    	<% else %>
	    		<div class="offer-reply-form" style="display:none" data-id="<%= offer.id %>"></div>
	    	<% end %> <!-- if current user replied offer -->
	    <% end %> <!-- if current user did not create offer -->
	<% end %> <!-- if current user -->

app/views/offers/about.html.erb
	<figure class="figure">
		<img id="we" class="figure-img img-rounded" src="/we.jpg" alt="authors">
		<figcaption class="figure-caption">Это мы</figcaption>
	</figure>

	<a href="http://vk.com/aikrik">Крикунов Александр</a>: Логика и интеграция
	<br>
	<a href="http://vk.com/nkomolov">Николай Комолов</a>: Верстка

app/views/offers/destroy.js.erb
$('.offer[data-id=<%= @offer.id %>]').remove()
$('.replies-offer[data-id=<%= @offer.id %>]').remove()

app/views/offers/index.html.erb
<div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <% if current_user %> <!-- offer form -->
                    <div class="media media-style">
                        <div class="media-left">
                            <%= avatar(current_user) %>    
                        </div>
                        <div class="media-body">
                                    <%= form_for(Offer.new) do |f| %>
                                    <%= f.text_area :content, class: "form-control", maxlength: "140" %>
                                    <div class="media-controls">
                                        <%= f.submit t('offer'), id: "btn-offer-submit", class: "btn-media-control btn btn-primary" %>
                                    </div>
                                <% end %>
                        </div> <!-- /.media-body -->
                    </div>
                <% end %>

                <% if @offers.length > 0 %> <!-- offers list -->
                    <div class="offer-list">
                        <%= render partial: "offer", collection: @offers %>
                    </div>
                <% else %>
                    <div class="empty-offer-list">
                        <%= t('no_offers') %>
                    </div>
                <% end %>
        </div> <!-- /.col -->
    </div> <!-- /.row -->
</div> <!-- /.container -->

app/views/offers/mine.html.erb
<% if @offers.length > 0 %>
  <div class="offer-list">
    <%= render partial: "mine_offer", collection: @offers %>
  </div>
<% else %>
  <div class="empty-offer-list">
    <%= t('no_mine_offers') %>
  </div>
<% end %>

app/views/replies/_offer.html.erb
<div
	class="replies-offer <%= offer == @offer ? 'offer-active' : '' %>"
	data-id="<%= offer.id %>"
	data-behavior="choose-replies-li">
		<div>
			<div class="replies-offer-tag-wrapper">
				<div class="offer-content" data-behavior="clamp">
				    <%= offer.content %>
				</div> <!-- /.replies-offer-tag-wrapper -->
				<% if new_replies_offer(offer) > 0 %>
					<span class="tag tag-pill tag-warning reply-count"><%= new_replies_offer offer %></span>
				<% end %>
			</div>
			<div class="replies-created-at" data-id="<%= offer.id %>">
			    <%= pretty_time offer.created_at %><br>
			    <% if not offer.accepted %>
			    	<span class="on-moderation"><%= t('on_moderation') %></span>
			    <% end %>
			</div>
			<div>
	        <%= link_to t('delete'),
	            offer_path(offer),
	            remote: true,
	            method: :delete,
	            class: "replies-offer-delete",
	            data: { confirm: t('sure') } 	%>
	      	</div>
		</div>
		

		<%= link_to "", choose_replies_path(offer_id: offer.id), remote: true, "data-behavior": "choose-replies", method: :get, style: "display:none" %>
</div>

app/views/replies/_read_link.html.erb
<%= link_to "", read_replies_path(ids: replies.ids, offer_id: offer.id), remote: true, method: :patch, "data-behavior": "read-replies", style: "display:none" %>

app/views/replies/_reply.html.erb
<div class="media replies-reply <%= !reply.seen ? 'reply-new' : '' %>">
    <div class="media-left">
        <%= avatar(reply.user) %>
    </div> <!-- /.media-left -->
    <div class="media-body">
        <div class="reply-link">
            <%= user_link(reply.user) %>
        </div>
        <div class="replies-offer-tag-wrapper">
            <div class="reply-message">
                <%= reply.message %>
            </div>
            <% if !reply.seen %>
                <span class="tag tag-pill tag-warning reply-count">Новый</span>
            <% end %>
        </div>
        <div class="created-at">
            <%= pretty_time reply.created_at %>
        </div>
    </div> <!-- /.media-body -->
</div>

app/views/replies/choose.js.erb
<% if @offers.length > 0 %>
  $(".replies-offer-list").html("<%= j (render partial: 'offer', collection: @offers) %>")
<% else %>
  $(".replies-offer-list").html("<div class='replies-offer-list-empty'><%= j t('no_mine_offers') %></div>")
<% end %>

<% if @replies.length > 0 %>
  $(".replies-reply-list").html("<%= j (render partial: 'reply', collection: @replies) %>")
<% else %>
  $(".replies-reply-list").html("<div class='replies-reply-list-empty'><%= j t('no_replies') %></div>")
<% end %>

// break words on replies and limit to 2 lines with added dots after last line
$('.offer-content[data-behavior~=clamp]').each(function(index, element) {
  $clamp(element, { clamp: 2, useNativeClamp: false });
});

$("[data-behavior~=read-replies]").replaceWith("<%= j (render partial: 'read_link', locals: {replies: @replies, offer: @offer}) %>")

setTimeout(function(){
	$("[data-behavior~=read-replies]").trigger("click")
}), 1000

app/views/replies/create.js.erb
$(".offer-reply-form[data-id=<%= @offer.id %>]").replaceWith("<%= j (render partial: 'offers/offer_reply_form', locals: {offer: @offer}) %>")
$(".offer-reply[data-id=<%= @offer.id %>]").replaceWith("<%= j (render partial: 'offers/offer_reply', locals: {offer: @offer}) %>")

// break words on replies and limit to 2 lines with added dots after last line
$('.offer-content').each(function(index, element) {
  $clamp(element, { clamp: 2, useNativeClamp: false });
});

app/views/replies/destroy.js.erb
$(".offer-reply-form[data-id=<%= @offer.id %>]").replaceWith("<%= j (render partial: 'offers/offer_reply_form', locals: {offer: @offer}) %>")
$(".offer-reply[data-id=<%= @offer.id %>]").replaceWith("<%= j (render partial: 'offers/offer_reply', locals: {offer: @offer}) %>")

// break words on replies and limit to 2 lines with added dots after last line
$('.offer-content').each(function(index, element) {
  $clamp(element, { clamp: 2, useNativeClamp: false });
});

app/views/replies/index.html.erb
<div class="container">
  <div class="row replies-box">
    <div class="col-xs-12 col-md-4">
      <% if @offers.length > 0 %>
        <div class="replies-offer-list">
          <%= render partial: "offer", collection: @offers %>
        </div>
      <% else %>
        <div class="replies-offer-list">
          <div class="replies-offer-list-empty"><%= t('no_mine_offers') %></div>
        </div>
      <% end %>
    </div> <!-- /.col-xs-12 -->

    <div class="col-xs-12 col-md-8">
      <% if @replies.length > 0 %>
        <div class="replies-reply-list">  
          <%= render partial: "reply", collection: @replies %>
        </div>
      <% else %>
        <div class="replies-reply-list">
          <div class="replies-reply-list-empty"><%= t('no_replies') %></div>
        </div>
      <% end %>
    </div> <!-- /.col-xs-12 -->
  </div> <!-- /.row -->
</div> <!-- /.container -->
<% if new_replies > 0 %>
  <%= link_to "", read_replies_path(ids: @replies.ids, offer_id: @offer.id), remote: true, method: :patch, "data-behavior": "read-replies", style: "display:none" %>
<% end %>

app/views/replies/read.js.erb
<% if @offers.length > 0 %>
  $(".replies-offer-list").html("<%= j (render partial: 'offer', collection: @offers) %>")
<% else %>
  $(".replies-offer-list").html("<div class='replies-offer-list-empty'><%= j t('no_mine_offers') %></div>")
<% end %>

<% if @replies.length > 0 %>
  $(".replies-reply-list").html("<%= j (render partial: 'reply', collection: @replies) %>")
<% else %>
  $(".replies-reply-list").html("<div class='replies-reply-list-empty'><%= j t('no_replies') %></div>")
<% end %>

$(".navbar").replaceWith("<%= j (render partial: 'layouts/navbar') %>")

// break words on replies and limit to 2 lines with added dots after last line
$('.offer-content').each(function(index, element) {
  $clamp(element, { clamp: 2, useNativeClamp: false });
});

app/views/users/avatars.js.erb
$('#gallery-links').html('')

<% @photos.each do |photo| %>
    var link = document.createElement("a")
    link.href = "<%= photo %>"
    $('#gallery-links').append(link)
<% end %>

blueimp.Gallery($('#gallery-links a'))